services:
    - docker

before_install:
    - docker --version

addons:
  apt:
    packages:
      - docker-ce

install:
    - git clone https://github.com/docker-library/official-images.git official-images

script:
    - docker build -t "$IMAGE_SLUG:latest" ./theia-latest;
    - docker build -t "$IMAGE_SLUG:next" ./theia-next;

after_script:
    - docker inspect "$IMAGE_SLUG:latest"
    - docker inspect "$IMAGE_SLUG:next"    
    - docker images
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" -o -n "$TRAVIS_TAG" ]; then 
    echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin;
    docker push "$IMAGE_SLUG:next" && docker push "$IMAGE_SLUG:latest";
    fi