sudo: required

services:
  - docker
  
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

git:
  depth: 1

language: generic


install:

  - docker build . -t chinodesuuu/theia:latest --no-cache
  - docker tag chinodesuuu/theia:latest

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push chinodesuuu/theia:latest
  on:
    branch: master
  skip_cleanup: true

notifications:
  on_success: change
  on_failure: always
  on_start: never