services:
    - docker

before_install:
    - docker --version

addons:
  apt:
    packages:
      - docker-ce

install:
    - git clone https://github.com/docker-library/official-images.git official-images


before_script:
    - image="chinodesuuu/theia-osio"
    - if [ -n "$TRAVIS_TAG" ]; then
      image="$image:$TRAVIS_TAG";
      fi
script:
    - docker build -t "$image" .
    - official-images/test/run.sh "$image"

after_script:
    - docker inspect "$image"    

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" -o -n "$TRAVIS_TAG" ]; then 
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$image";
    fi
