#!/bin/bash 
export HOME=/home/theia
export USER_ID=$(id -u)
export GROUP_ID=$(id -g)
export alias node="node --expose-gc --max-old-space-size=64 --max-new-space-size=256"

if [ -w /etc/passwd ]; then
  echo "default:x:$(id -u):$(id -g):default user:${HOME}:/sbin/nologin" >> /etc/passwd
fi
exec "$@"
